### ISSUE TITLE
Adding Integration results in error

### ISSUE THREAD

**Issue by csrui** [dgomes/ha_erse#12]
Going to Integrations > + > "Entidade Reguladora..." results in a "Config Flow could not be loaded".

Request: http://x.x.x.x:8123/api/config/config_entries/flow
```
HTTP/1.1 500 Internal Server Error
Date: Thu, 05 Aug 2021 17:42:34 GMT
Content-Type: text/plain; charset=utf-8
Connection: close
Content-Length: 55
Server: Python/3.9 aiohttp/3.7.4.post0
```

At the time of writing, both Home Assistant and your integration (via HACS) are up to date. Let me know if I can test anything to help.

**Comment by dgomes** [comment]
depois da versão 1.1 é preciso reconfigurar o ERSE (apagar e criar de novo)

**Comment by csrui** [comment]
Eu tinha o custom component instalado mas não me recordo de já ter feito a integração no passado. 
Removi o componente, fiz restart, voltei a adicionar o componente, novo restart. Quando vou adicionar a integração, falha como indicado acima. Haverá alguma entrada em algum ficheiro que seja necessário remover?

**Comment by dgomes** [comment]
podes entrar no discord do CPHA e procurar por mim ?

**Comment by csrui** [comment]
Hoje não devo conseguir, por isso deixo aqui mais feedback.

Ao tentar adicionar a integração tenho 3 entradas no log.

```
Logger: homeassistant.setup
Source: components/utility_meter/__init__.py:67 
First occurred: 21:33:00 (1 occurrences) 
Last logged: 21:33:00

Error during setup of component utility_meter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 249, in _async_setup_component
    result = await task
  File "/usr/src/homeassistant/homeassistant/components/utility_meter/__init__.py", line 67, in async_setup
    for meter, conf in config.get(DOMAIN).items():
AttributeError: 'NoneType' object has no attribute 'items'
```

```
Logger: homeassistant.setup
Source: setup.py:153 
First occurred: 21:33:00 (1 occurrences) 
Last logged: 21:33:00

Unable to set up dependencies of erse. Setup failed for dependencies: utility_meter
```

```
Logger: aiohttp.server
Source: setup.py:371 
First occurred: 21:33:00 (1 occurrences) 
Last logged: 21:33:00

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 128, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 171, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 693, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 371, in async_process_deps_reqs
    raise HomeAssistantError("Could not set up all dependencies.")
homeassistant.exceptions.HomeAssistantError: Could not set up all dependencies.
```

**Comment by dgomes** [comment]
ainda com problemas ?

**Comment by diegomontanaduarte** [comment]
Estou com o mesmo problema ao tentar adicionar esta integração no Home Assistant

**Comment by dgomes** [comment]
> Estou com o mesmo problema ao tentar adicionar esta integração no Home Assistant

Mesmo erro nos logs ?

**Comment by diegomontanaduarte** [comment]
Segue sequência de eventos e logs ao tentar adicionar a integração

![image](https://user-images.githubusercontent.com/2682853/133803991-345c3a20-78b6-4690-8315-250e1484045a.png)

![image](https://user-images.githubusercontent.com/2682853/133804023-c9865ba1-f274-4442-a4b8-068bb21606b1.png)

![image](https://user-images.githubusercontent.com/2682853/133804039-f749cd4f-6cab-43d5-8a5f-ddcb1b5821e2.png)



Logger: aiohttp.server
Source: setup.py:377
First occurred: 3:52:04 PM (1 occurrences)
Last logged: 3:52:04 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 89, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 128, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 171, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 707, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 377, in async_process_deps_reqs
    raise HomeAssistantError("Could not set up all dependencies.")
homeassistant.exceptions.HomeAssistantError: Could not set up all dependencies.




Logger: homeassistant.setup
Source: setup.py:159
First occurred: 3:52:04 PM (1 occurrences)
Last logged: 3:52:04 PM

Unable to set up dependencies of erse. Setup failed for dependencies: utility_meter



Logger: homeassistant.setup
Source: components/utility_meter/__init__.py:97
First occurred: 3:52:04 PM (1 occurrences)
Last logged: 3:52:04 PM

Error during setup of component utility_meter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 255, in _async_setup_component
    result = await task
  File "/usr/src/homeassistant/homeassistant/components/utility_meter/__init__.py", line 97, in async_setup
    for meter, conf in config.get(DOMAIN).items():
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by dgomes** [comment]
@diegomontanaduarte Tens um utility_meter configurado ?

Qual a configuração ?

**Comment by diegomontanaduarte** [comment]
@dgomes Desculpe Diogo não tinha a integração do Utility Meter em no arquivo configuration.yaml. Achei um pouco confuso todo esse processo inicial de configuração. Agora tenho o ERSE configurado, pode me dizer se essa é a configuração correta 
para a nova feature Energy do Home Assistant? 

No ERSE o campo "Cost of Power (day)" é a o valor da Potência Contratada?

![image](https://user-images.githubusercontent.com/2682853/133819999-6c7b5ea9-fbb1-4a6a-99a7-6414c2165ffd.png)

**Comment by dgomes** [comment]
O ERSE produz 3 sensores no caso do bi-horario

Assim deve se usar o sensor do utility_meter correspondente a cada tarifa (Vazio, Fora_de_Vazio) e o sensor de custo correspondente

O sensor de custo que tem ai é o sensor de custo fixo diário (custo da potencia disponível + impostos + taxas)

**Comment by diegomontanaduarte** [comment]
Após ler algumas documentações e alguns artigos na internet eu consegui entender o conceito da integração. Obrigado Diogo!

**Comment by romeupaz** [comment]
Uma pergunta, tendo o custom_config no configuration.yaml dá para adicionar esta integração ou tenho de fazer tudo à mão?

**Comment by dgomes** [comment]
configuração por yaml está **deprecada**
