### ISSUE TITLE
AttributeError: 'NetMeterSensor' object has no attribute 'friendly_name'

### ISSUE THREAD

**Issue by ostracizado** [dgomes/ha_erse#35]
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/erse/sensor.py:305
Integration: Entidade Reguladora dos Serviços Energéticos (documentation, issues)
First occurred: 27 January 2024 at 00:00:00 (97 occurrences)
Last logged: 00:00:00

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/erse/sensor.py", line 305, in timer_update
    self.friendly_name,
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NetMeterSensor' object has no attribute 'friendly_name'
```

**Comment by dgomes** [comment]
Podes partilhar a tua configuração ?

**Comment by ostracizado** [comment]
Não estou a conseguir replicar o erro; mas suspeito estar relacionado com um utility_sensor que configurei pelo helpers GUI, recentemente, para fazer reset a 26 de cada mês.

Há alguma forma de visualizar a configuração em estilo yaml de tais configurações GUI?

**Comment by dgomes** [comment]
não... as mesmas ficam num json na pasta /config/.storage/core.config_entries

**Comment by cmgestevao** [comment]
Este erro teve origem numa integração personalizada.

Logger: homeassistant
Origem: custom_components/erse/sensor.py:304
integração: Entidade Reguladora dos Serviços Energéticos (documentação, problemas)
Primeira ocorrência: 00:00:01 (90 ocorrências)
Último registo: 22:15:00

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/erse/sensor.py", line 304, in timer_update
    self.friendly_name,
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NetMeterSensor' object has no attribute 'friendly_name'

Olá, de 15 em 15 minutos sai isto no log. Se reiniciar o HA deixa de aparecer, mas a partir das 00:00:00 volta a aparecer de 15 em 15 minutos.

No ficheiro "core.config_entries" referido anteriormente, apenas encontro os valores configurados da energia e da potência!
